const assert = require('assert');
const fs = require('fs');
const path = require('path');

const repo = path.resolve(__dirname, '..', '..', '..', '..');
const appSource = fs.readFileSync(path.join(repo, 'project/src/app/App.tsx'), 'utf8');

assert.ok(appSource.includes('createBridgeClient'), 'App uses the production bridge client');
assert.ok(appSource.includes('currentIngestStatus'), 'App requests current ingest status');
assert.ok(appSource.includes('initDemoReceiverSession'), 'App initializes managed receiver session');
assert.ok(appSource.includes('demoReceiverTick'), 'App requests session-backed receiver tick event');
assert.ok(appSource.includes('dataRef'), 'App displays dataRef from bridge event');
assert.ok(appSource.includes('acceptedSamples'), 'App displays accepted sample counters');
assert.ok(appSource.includes('setInterval'), 'App refreshes live bridge status periodically');
assert.ok(appSource.includes('clearInterval'), 'App clears live bridge status polling');
assert.ok(appSource.includes('Channel Explorer'), 'App includes workstation channel explorer region');
assert.ok(appSource.includes('CHANNEL_GROUPS'), 'App uses typed mock channel metadata');
assert.ok(appSource.includes('searchChannels'), 'App uses channel search helper');
assert.ok(appSource.includes('placeholder="search channels"'), 'App renders channel search input');
assert.ok(appSource.includes('filteredChannels'), 'App renders filtered channel results');
assert.ok(appSource.includes('subscribePanelData'), 'App subscribes selected channels through bridge');
assert.ok(appSource.includes('selectedSubscription'), 'App stores selected subscription handle');
assert.ok(appSource.includes('selectedChannel'), 'App stores selected channel metadata');
assert.ok(appSource.includes('writeDemoCsvExport'), 'App can write CSV export job');
assert.ok(appSource.includes('bridge.listJobs'), 'App refreshes backend jobs after export');
assert.ok(appSource.includes('ExportPanel'), 'App renders export preview panel');
assert.ok(appSource.includes('csvPath'), 'App displays CSV export path');
assert.ok(appSource.includes('qualityPolicy'), 'App displays export manifest quality policy');
assert.ok(appSource.includes('valueMode'), 'App displays export manifest value mode');
assert.ok(appSource.includes('rowCount'), 'App displays export manifest row count');
assert.ok(appSource.includes('Main Workspace'), 'App includes workstation workspace region');
assert.ok(appSource.includes('Insight Pane'), 'App includes workstation insight pane region');
assert.ok(appSource.includes('LLMTracePanel'), 'App renders LLM evidence trace panel');
assert.ok(appSource.includes('validateDemoLlmAnswer'), 'App validates LLM answer citations through bridge');
assert.ok(appSource.includes('buildDemoOllamaRequest'), 'App can preview Ollama request payload');
assert.ok(appSource.includes('Manual LLM'), 'App labels slow LLM invocation as manual');
assert.ok(appSource.includes('developer laptop'), 'App warns about developer laptop LLM latency');
assert.ok(appSource.includes('onManualLlm'), 'LLM trace exposes manual action callback');
assert.ok(appSource.includes('Refresh LLM Preview'), 'App renders manual LLM preview refresh button');
assert.ok(appSource.includes('Queued jobs'), 'App displays queued background job count');
assert.ok(appSource.includes('enqueueDemoLlmJob'), 'App queues manual LLM jobs through bridge');
assert.ok(appSource.includes('listJobs'), 'App reads backend job queue through bridge');
assert.ok(appSource.includes('JobPanel'), 'App renders backend job panel');
assert.ok(appSource.includes('markJobRunning'), 'JobPanel can mark jobs running');
assert.ok(appSource.includes('markJobCompleted'), 'JobPanel can mark jobs completed');
assert.ok(appSource.includes('markJobFailed'), 'JobPanel can mark jobs failed');
assert.ok(appSource.includes('selectedRootCause?.nodeId'), 'App passes selected root cause into LLM validation');
assert.ok(appSource.includes('demoRootCauseCandidates'), 'App requests root cause candidates through bridge');
assert.ok(appSource.includes('RootCauseCandidates'), 'App renders root cause candidates');
assert.ok(appSource.includes('evidenceEdges'), 'App displays root cause evidence edge details');
assert.ok(appSource.includes('edgeLabels'), 'App maps evidence edge details to operator labels');
assert.ok(appSource.includes('evidenceSummary'), 'App displays root cause evidence summary');
assert.ok(appSource.includes('selectedRootCause'), 'App stores selected root cause candidate');
assert.ok(appSource.includes('onSelect'), 'RootCauseCandidates supports selection callback');
assert.ok(appSource.includes('subscribeRootCauseChannel'), 'App can subscribe related channel from root cause candidate');
assert.ok(appSource.includes('missing'), 'App displays missing LLM citations');
assert.ok(appSource.includes('Bottom Status'), 'App includes bottom status console region');
assert.ok(appSource.includes('TelemetryPanel'), 'App uses a production telemetry panel component');
assert.ok(appSource.includes('synthetic replay fixture'), 'App labels demo evidence as synthetic replay fixture');
assert.ok(appSource.includes('ManagedReceiverPanel'), 'App renders managed UDP receiver loop status');
assert.ok(appSource.includes('startManagedReceiverLoop'), 'App starts managed UDP receiver loop through bridge');
assert.ok(appSource.includes('stopManagedReceiverLoop'), 'App stops managed UDP receiver loop through bridge');
assert.ok(appSource.includes('managedProfile'), 'App stores operator-managed UDP profile');
assert.ok(appSource.includes('bindIp'), 'App exposes managed receiver bind IP');
assert.ok(appSource.includes('bindPort'), 'App exposes managed receiver bind port');
assert.ok(appSource.includes('expectedBitrateMbps'), 'App exposes managed receiver bitrate');
assert.ok(appSource.includes('managedReceiverStatus'), 'App reads managed UDP receiver status through bridge');
assert.ok(appSource.includes('drainManagedReceiverEvents'), 'App drains managed UDP receiver events through bridge');
assert.ok(appSource.includes('Managed UDP Loop'), 'App labels managed receiver runtime panel');
assert.ok(appSource.includes('runtime.action'), 'App displays runtime next actions');
assert.ok(appSource.includes('demoSimdisBridgeStatus'), 'App reads SimDIS bridge status through bridge');
assert.ok(appSource.includes('SimdisBridgePanel'), 'App renders SimDIS bridge panel');
assert.ok(appSource.includes('SimDIS Bridge'), 'App labels SimDIS bridge panel');
assert.ok(appSource.includes('demoVideoSyncEvent'), 'App reads video sync event through bridge');
assert.ok(appSource.includes('MapVideoSyncPanel'), 'App renders map/video sync panel');
assert.ok(appSource.includes('Map / Video Sync'), 'App labels map/video sync panel');
assert.ok(appSource.includes('prepareDemoMatlabHandoff'), 'App prepares MATLAB handoff through bridge');
assert.ok(appSource.includes('enqueueDemoMatlabJob'), 'App queues MATLAB handoff jobs through bridge');
assert.ok(appSource.includes('MatlabHandoffPanel'), 'App renders MATLAB handoff panel');
assert.ok(appSource.includes('MATLAB Handoff'), 'App labels MATLAB handoff panel');
assert.ok(appSource.includes('DataRefPanel'), 'App uses a dataRef panel component');
assert.ok(appSource.includes('RealTimeInsight'), 'App preserves product signal');

console.log('App contract tests passed');
